services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: magnexis
      POSTGRES_USER: magnexis
      POSTGRES_PASSWORD: magnexis
    ports:
      - "5432:5432"
    volumes:
      - magnexis-postgres:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  magnexis-postgres:

